import "server-only";
import { cache } from "react";
import { all,first } from "@/lib/db/query";
import { mediaUrl } from "@/lib/storage/r2";
import type { BlogPost } from "@/types/blog-post";
type BlogRow={id:string;title:string;slug:string;excerpt:string|null;content:string|null;cover_image_path:string|null;status:string;published_at:string|null;seo_title:string|null;seo_description:string|null;created_at:string;updated_at:string};
function blog(row:BlogRow):BlogPost{return{id:row.id,title:row.title,slug:row.slug,excerpt:row.excerpt??"",image:row.cover_image_path?mediaUrl(row.cover_image_path):"/images/home/about-placeholder.svg",imageAlt:`${row.title} yazı görseli`,category:"Gezi Rehberi",publishedAt:(row.published_at??row.created_at).slice(0,10),readingTime:Math.max(1,Math.ceil((row.content?.split(/\s+/).length??0)/200)),featured:false,order:0,relatedTourSlugs:[],status:"published"};}
export const getPublishedBlogPosts=cache(async()=>all<BlogRow>("SELECT * FROM blog_posts WHERE status='published' ORDER BY published_at DESC,created_at DESC").then(rows=>rows.map(blog)));
export const getPublishedBlogPostBySlug=cache(async(slug:string)=>{const row=await first<BlogRow>("SELECT * FROM blog_posts WHERE slug=? AND status='published'",[slug]);return row?{post:blog(row),content:row.content??row.excerpt??"",seoTitle:row.seo_title,seoDescription:row.seo_description,updatedAt:row.updated_at}:null;});
export type PublicDestination={id:string;name:string;slug:string;shortDescription:string;content:string;seoTitle:string|null;seoDescription:string|null;updatedAt:string};
export const getPublishedDestinationBySlug=cache(async(slug:string)=>{const row=await first<{id:string;name:string;slug:string;short_description:string|null;content:string|null;seo_title:string|null;seo_description:string|null;updated_at:string}>("SELECT id,name,slug,short_description,content,seo_title,seo_description,updated_at FROM destinations WHERE slug=? AND status='published'",[slug]);return row?{id:row.id,name:row.name,slug:row.slug,shortDescription:row.short_description??"Bu destinasyona ait tur içerikleri hazırlanıyor.",content:row.content??"",seoTitle:row.seo_title,seoDescription:row.seo_description,updatedAt:row.updated_at}:null;});
export async function getPublishedSitemapEntries(){const[tours,blogs,destinations]=await Promise.all([all<{slug:string;updated_at:string}>("SELECT slug,updated_at FROM tours WHERE status='published'"),all<{slug:string;updated_at:string}>("SELECT slug,updated_at FROM blog_posts WHERE status='published'"),all<{slug:string;updated_at:string}>("SELECT slug,updated_at FROM destinations WHERE status='published'")]);return{tours,blogs,destinations};}
