"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/session";
import { all,batch,first,run } from "@/lib/db/query";
import { faqSchema,hotelSchema,importantNoteSchema,itinerarySchema,serviceSchema,serviceTypeSchema,type FaqInput,type HotelInput,type ImportantNoteInput,type ItineraryInput,type ServiceInput } from "@/lib/validation/tour-content";
export type ContentActionResult={success:boolean;message:string;fieldErrors:Record<string,string>}; type Direction="previous"|"next";type ServiceType=z.infer<typeof serviceTypeSchema>;
const uuid=z.uuid(),ok=(message:string):ContentActionResult=>({success:true,message,fieldErrors:{}}),fail=(message="İşlem tamamlanamadı. Lütfen tekrar deneyin.",fieldErrors:Record<string,string>={}):ContentActionResult=>({success:false,message,fieldErrors});
function validation(error:z.ZodError){const fields:Record<string,string>={};for(const issue of error.issues){const key=issue.path.join(".");if(key&&!fields[key])fields[key]=issue.message;}return fail("Form alanlarını kontrol edin.",fields);}async function guard(tourId:string,id?:string){await requireAdmin();return uuid.safeParse(tourId).success&&(!id||uuid.safeParse(id).success)&&Boolean(await first("SELECT id FROM tours WHERE id=?",[tourId]));}function refresh(id:string){revalidatePath(`/admin/turlar/${id}`);}const now=()=>new Date().toISOString();
async function next(table:string,tourId:string,column:string){return((await first<{value:number|null}>(`SELECT MAX(${column}) value FROM ${table} WHERE tour_id=?`,[tourId]))?.value??(column==="day_number"?0:-1))+1;}
async function move(table:string,column:string,tourId:string,id:string,direction:Direction,filter="",values:readonly unknown[]=[]){const rows=await all<{id:string;position:number}>(`SELECT id,${column} position FROM ${table} WHERE tour_id=? ${filter} ORDER BY ${column}`,[tourId,...values]);const index=rows.findIndex(r=>r.id===id),target=direction==="previous"?index-1:index+1;if(index<0||target<0||target>=rows.length)return false;const temp=Math.max(...rows.map(r=>r.position))+1000;await batch([{sql:`UPDATE ${table} SET ${column}=? WHERE id=? AND tour_id=?`,values:[temp,rows[index].id,tourId]},{sql:`UPDATE ${table} SET ${column}=? WHERE id=? AND tour_id=?`,values:[rows[index].position,rows[target].id,tourId]},{sql:`UPDATE ${table} SET ${column}=? WHERE id=? AND tour_id=?`,values:[rows[target].position,rows[index].id,tourId]}]);return true;}
async function remove(table:string,column:string,tourId:string,id:string,filter="",values:readonly unknown[]=[]){const deleted=await run(`DELETE FROM ${table} WHERE id=? AND tour_id=?`,[id,tourId]);if(!deleted.meta.changes)return false;const rows=await all<{id:string}>(`SELECT id FROM ${table} WHERE tour_id=? ${filter} ORDER BY ${column}`,[tourId,...values]);await batch(rows.map((r,i)=>({sql:`UPDATE ${table} SET ${column}=? WHERE id=?`,values:[column==="day_number"?i+1:i,r.id]})));return true;}
export async function createItineraryDayAction(tourId:string,input:ItineraryInput){if(!await guard(tourId))return fail();const p=itinerarySchema.safeParse(input);if(!p.success)return validation(p.error);if(p.data.image_path&&!await first("SELECT id FROM tour_gallery WHERE tour_id=? AND storage_path=?",[tourId,p.data.image_path]))return fail("Seçilen görsel bu tura ait değil.");const stamp=now();await run("INSERT INTO tour_itinerary_days (id,tour_id,day_number,title,route,summary,description,image_path,image_alt,highlights,transportation,accommodation,meals,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[crypto.randomUUID(),tourId,await next("tour_itinerary_days",tourId,"day_number"),p.data.title,p.data.route,p.data.summary,p.data.description,p.data.image_path,p.data.image_alt,JSON.stringify(p.data.highlights),p.data.transportation,p.data.accommodation,p.data.meals,stamp,stamp]);refresh(tourId);return ok("Program günü eklendi.");}
export async function updateItineraryDayAction(tourId:string,id:string,input:ItineraryInput){if(!await guard(tourId,id))return fail();const p=itinerarySchema.safeParse(input);if(!p.success)return validation(p.error);if(p.data.image_path&&!await first("SELECT id FROM tour_gallery WHERE tour_id=? AND storage_path=?",[tourId,p.data.image_path]))return fail("Seçilen görsel bu tura ait değil.");const result=await run("UPDATE tour_itinerary_days SET title=?,route=?,summary=?,description=?,image_path=?,image_alt=?,highlights=?,transportation=?,accommodation=?,meals=?,updated_at=? WHERE id=? AND tour_id=?",[p.data.title,p.data.route,p.data.summary,p.data.description,p.data.image_path,p.data.image_alt,JSON.stringify(p.data.highlights),p.data.transportation,p.data.accommodation,p.data.meals,now(),id,tourId]);if(!result.meta.changes)return fail();refresh(tourId);return ok("Program günü güncellendi.");}
export async function moveItineraryDayAction(tourId:string,id:string,direction:Direction){if(!await guard(tourId,id)||!await move("tour_itinerary_days","day_number",tourId,id,direction))return fail("Program günü bu yönde taşınamaz.");refresh(tourId);return ok("Program sırası güncellendi.");}
export async function deleteItineraryDayAction(tourId:string,id:string){if(!await guard(tourId,id)||!await remove("tour_itinerary_days","day_number",tourId,id))return fail();const count=(await first<{count:number}>("SELECT COUNT(*) count FROM tour_itinerary_days WHERE tour_id=?",[tourId]))?.count??0;await run("DELETE FROM tour_day_transfers WHERE tour_id=? AND (from_day_number>=? OR to_day_number>?)",[tourId,count,count]);refresh(tourId);return ok("Program günü silindi.");}
export async function createHotelAction(tourId:string,input:HotelInput){if(!await guard(tourId))return fail();const p=hotelSchema.safeParse(input);if(!p.success)return validation(p.error);await run("INSERT INTO tour_hotels (id,tour_id,city,night_count,hotel_name,stars,sort_order) VALUES (?,?,?,?,?,?,?)",[crypto.randomUUID(),tourId,p.data.city,p.data.night_count,p.data.hotel_name,p.data.stars,await next("tour_hotels",tourId,"sort_order")]);refresh(tourId);return ok("Konaklama eklendi.");}
export async function updateHotelAction(tourId:string,id:string,input:HotelInput){if(!await guard(tourId,id))return fail();const p=hotelSchema.safeParse(input);if(!p.success)return validation(p.error);if(!(await run("UPDATE tour_hotels SET city=?,night_count=?,hotel_name=?,stars=? WHERE id=? AND tour_id=?",[p.data.city,p.data.night_count,p.data.hotel_name,p.data.stars,id,tourId])).meta.changes)return fail();refresh(tourId);return ok("Konaklama güncellendi.");}
export async function moveHotelAction(tourId:string,id:string,direction:Direction){if(!await guard(tourId,id)||!await move("tour_hotels","sort_order",tourId,id,direction))return fail("Konaklama bu yönde taşınamaz.");refresh(tourId);return ok("Konaklama sırası güncellendi.");}export async function deleteHotelAction(tourId:string,id:string){if(!await guard(tourId,id)||!await remove("tour_hotels","sort_order",tourId,id))return fail();refresh(tourId);return ok("Konaklama silindi.");}
export async function createServiceAction(tourId:string,type:ServiceType,input:ServiceInput){if(!await guard(tourId)||!serviceTypeSchema.safeParse(type).success)return fail();const p=serviceSchema.safeParse(input);if(!p.success)return validation(p.error);await run("INSERT INTO tour_service_items (id,tour_id,type,content,sort_order,created_at) VALUES (?,?,?,?,?,?)",[crypto.randomUUID(),tourId,type,p.data.content,await next("tour_service_items",tourId,"sort_order"),now()]);refresh(tourId);return ok("Hizmet maddesi eklendi.");}
export async function updateServiceAction(tourId:string,id:string,type:ServiceType,input:ServiceInput){if(!await guard(tourId,id))return fail();const p=serviceSchema.safeParse(input);if(!p.success)return validation(p.error);if(!(await run("UPDATE tour_service_items SET content=? WHERE id=? AND tour_id=? AND type=?",[p.data.content,id,tourId,type])).meta.changes)return fail();refresh(tourId);return ok("Hizmet maddesi güncellendi.");}
export async function moveServiceAction(tourId:string,id:string,type:ServiceType,direction:Direction){if(!await guard(tourId,id)||!await move("tour_service_items","sort_order",tourId,id,direction,"AND type=?",[type]))return fail("Hizmet maddesi bu yönde taşınamaz.");refresh(tourId);return ok("Hizmet sırası güncellendi.");}export async function deleteServiceAction(tourId:string,id:string,type:ServiceType){if(!await guard(tourId,id)||!await remove("tour_service_items","sort_order",tourId,id,"AND type=?",[type]))return fail();refresh(tourId);return ok("Hizmet maddesi silindi.");}
export async function createImportantNoteAction(tourId:string,input:ImportantNoteInput){if(!await guard(tourId))return fail();const p=importantNoteSchema.safeParse(input);if(!p.success)return validation(p.error);const stamp=now();await run("INSERT INTO tour_important_notes (id,tour_id,title,content,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?)",[crypto.randomUUID(),tourId,p.data.title,p.data.content,await next("tour_important_notes",tourId,"sort_order"),stamp,stamp]);refresh(tourId);return ok("Önemli bilgi eklendi.");}
export async function updateImportantNoteAction(tourId:string,id:string,input:ImportantNoteInput){if(!await guard(tourId,id))return fail();const p=importantNoteSchema.safeParse(input);if(!p.success)return validation(p.error);if(!(await run("UPDATE tour_important_notes SET title=?,content=?,updated_at=? WHERE id=? AND tour_id=?",[p.data.title,p.data.content,now(),id,tourId])).meta.changes)return fail();refresh(tourId);return ok("Önemli bilgi güncellendi.");}
export async function moveImportantNoteAction(tourId:string,id:string,direction:Direction){if(!await guard(tourId,id)||!await move("tour_important_notes","sort_order",tourId,id,direction))return fail();refresh(tourId);return ok("Önemli bilgi sırası güncellendi.");}export async function deleteImportantNoteAction(tourId:string,id:string){if(!await guard(tourId,id)||!await remove("tour_important_notes","sort_order",tourId,id))return fail();refresh(tourId);return ok("Önemli bilgi silindi.");}
export async function createFaqAction(tourId:string,input:FaqInput){if(!await guard(tourId))return fail();const p=faqSchema.safeParse(input);if(!p.success)return validation(p.error);const stamp=now();await run("INSERT INTO tour_faqs (id,tour_id,question,answer,sort_order,published,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)",[crypto.randomUUID(),tourId,p.data.question,p.data.answer,await next("tour_faqs",tourId,"sort_order"),p.data.published?1:0,stamp,stamp]);refresh(tourId);return ok("SSS eklendi.");}
export async function updateFaqAction(tourId:string,id:string,input:FaqInput){if(!await guard(tourId,id))return fail();const p=faqSchema.safeParse(input);if(!p.success)return validation(p.error);if(!(await run("UPDATE tour_faqs SET question=?,answer=?,published=?,updated_at=? WHERE id=? AND tour_id=?",[p.data.question,p.data.answer,p.data.published?1:0,now(),id,tourId])).meta.changes)return fail();refresh(tourId);return ok("SSS güncellendi.");}
export async function toggleFaqPublishedAction(tourId:string,id:string,published:boolean){if(!await guard(tourId,id))return fail();if(!(await run("UPDATE tour_faqs SET published=?,updated_at=? WHERE id=? AND tour_id=?",[published?1:0,now(),id,tourId])).meta.changes)return fail();refresh(tourId);return ok(published?"SSS yayınlandı.":"SSS taslağa alındı.");}
export async function moveFaqAction(tourId:string,id:string,direction:Direction){if(!await guard(tourId,id)||!await move("tour_faqs","sort_order",tourId,id,direction))return fail();refresh(tourId);return ok("SSS sırası güncellendi.");}export async function deleteFaqAction(tourId:string,id:string){if(!await guard(tourId,id)||!await remove("tour_faqs","sort_order",tourId,id))return fail();refresh(tourId);return ok("SSS silindi.");}
