"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/session";
import { all,batch,first,run } from "@/lib/db/query";
import { IMAGE_MIME_EXTENSIONS,isImageMimeType,MAX_IMAGE_SIZE,MAX_PDF_SIZE } from "@/lib/storage/file-validation";
import { isValidTourStoragePath } from "@/lib/storage/path";
import { mediaExists,removeMedia } from "@/lib/storage/r2";
export type MediaActionResult={success:boolean;message:string};type Gallery={id:string;tour_id:string;storage_path:string;alt_text:string;sort_order:number;is_cover:number;created_at:string};const uuid=z.uuid(),alt=z.string().trim().min(3).max(180),success=(message:string):MediaActionResult=>({success:true,message}),failure=(message="İşlem tamamlanamadı. Lütfen tekrar deneyin."):MediaActionResult=>({success:false,message});function refresh(id:string){revalidatePath(`/admin/turlar/${id}`);revalidatePath("/admin/turlar");}async function tourExists(id:string){return Boolean(await first("SELECT id FROM tours WHERE id=?",[id]));}
export async function registerGalleryImageAction(input:{tourId:string;storagePath:string;altText:string;mimeType:string;fileSize:number}){await requireAdmin();const parsed=alt.safeParse(input.altText),validMime=isImageMimeType(input.mimeType),validPath=isValidTourStoragePath(input.storagePath,input.tourId,["jpg","png","webp","avif"]);if(!uuid.safeParse(input.tourId).success||!parsed.success||!validMime||!validPath||input.fileSize<=0||input.fileSize>MAX_IMAGE_SIZE||!input.storagePath.endsWith(`.${validMime?IMAGE_MIME_EXTENSIONS[input.mimeType]:""}`)||!await tourExists(input.tourId)||!await mediaExists(input.storagePath)){if(validPath)await removeMedia(input.storagePath);return failure("Görsel bilgileri geçersiz.");}if(await first("SELECT id FROM tour_gallery WHERE storage_path=?",[input.storagePath])){await removeMedia(input.storagePath);return failure("Bu görsel daha önce kaydedilmiş.");}const last=await first<{value:number|null}>("SELECT MAX(sort_order) value FROM tour_gallery WHERE tour_id=?",[input.tourId]),cover=(last?.value??null)===null,id=crypto.randomUUID();try{await batch([{sql:"INSERT INTO tour_gallery (id,tour_id,storage_path,alt_text,sort_order,is_cover,created_at) VALUES (?,?,?,?,?,?,?)",values:[id,input.tourId,input.storagePath,parsed.data,(last?.value??-1)+1,cover?1:0,new Date().toISOString()]},...(cover?[{sql:"UPDATE tours SET cover_image_path=?,updated_at=? WHERE id=?",values:[input.storagePath,new Date().toISOString(),input.tourId]}]:[])]);}catch{await removeMedia(input.storagePath);return failure();}refresh(input.tourId);return success("Görsel galeriye eklendi.");}
export async function updateGalleryAltTextAction(tourId:string,galleryId:string,value:string){await requireAdmin();const p=alt.safeParse(value);if(!p.success||!uuid.safeParse(tourId).success||!uuid.safeParse(galleryId).success)return failure("Geçersiz görsel kaydı.");if(!(await run("UPDATE tour_gallery SET alt_text=? WHERE id=? AND tour_id=?",[p.data,galleryId,tourId])).meta.changes)return failure();refresh(tourId);return success("Alt metin güncellendi.");}
export async function setTourCoverImageAction(tourId:string,galleryId:string){await requireAdmin();const selected=await first<Gallery>("SELECT * FROM tour_gallery WHERE id=? AND tour_id=?",[galleryId,tourId]);if(!selected)return failure("Görsel bu tura ait değil.");await batch([{sql:"UPDATE tour_gallery SET is_cover=0 WHERE tour_id=?",values:[tourId]},{sql:"UPDATE tour_gallery SET is_cover=1 WHERE id=? AND tour_id=?",values:[galleryId,tourId]},{sql:"UPDATE tours SET cover_image_path=?,updated_at=? WHERE id=?",values:[selected.storage_path,new Date().toISOString(),tourId]}]);refresh(tourId);return success("Kapak görseli güncellendi.");}
export async function moveGalleryImageAction(tourId:string,galleryId:string,direction:"previous"|"next"){await requireAdmin();const rows=await all<Gallery>("SELECT * FROM tour_gallery WHERE tour_id=? ORDER BY sort_order,created_at",[tourId]),index=rows.findIndex(r=>r.id===galleryId),target=direction==="previous"?index-1:index+1;if(index<0||target<0||target>=rows.length)return failure("Görsel bu yönde taşınamaz.");const temp=rows.length+1000;await batch([{sql:"UPDATE tour_gallery SET sort_order=? WHERE id=?",values:[temp,rows[index].id]},{sql:"UPDATE tour_gallery SET sort_order=? WHERE id=?",values:[rows[index].sort_order,rows[target].id]},{sql:"UPDATE tour_gallery SET sort_order=? WHERE id=?",values:[rows[target].sort_order,rows[index].id]}]);refresh(tourId);return success("Görsel sırası güncellendi.");}
export async function deleteGalleryImageAction(tourId:string,galleryId:string){await requireAdmin();const image=await first<Gallery>("SELECT * FROM tour_gallery WHERE id=? AND tour_id=?",[galleryId,tourId]);if(!image||!isValidTourStoragePath(image.storage_path,tourId,["jpg","png","webp","avif"]))return failure("Görsel bu tura ait değil.");try{await removeMedia(image.storage_path);}catch{return failure("Görsel dosyası silinemedi.");}await batch([{sql:"UPDATE tour_itinerary_days SET image_path=NULL,image_alt=NULL,updated_at=? WHERE tour_id=? AND image_path=?",values:[new Date().toISOString(),tourId,image.storage_path]},{sql:"DELETE FROM tour_gallery WHERE id=? AND tour_id=?",values:[galleryId,tourId]}]);const rows=await all<Gallery>("SELECT * FROM tour_gallery WHERE tour_id=? ORDER BY sort_order,created_at",[tourId]);const statements=rows.map((row,index)=>({sql:"UPDATE tour_gallery SET sort_order=? WHERE id=?",values:[index,row.id]}));if(image.is_cover){const next=rows[0];statements.push({sql:"UPDATE tours SET cover_image_path=?,updated_at=? WHERE id=?",values:[next?.storage_path??null,new Date().toISOString(),tourId]});if(next)statements.push({sql:"UPDATE tour_gallery SET is_cover=1 WHERE id=?",values:[next.id]});}if(statements.length)await batch(statements);refresh(tourId);return success("Görsel silindi.");}
export async function registerTourPdfAction(input:{tourId:string;storagePath:string;mimeType:string;fileSize:number}){await requireAdmin();const valid=isValidTourStoragePath(input.storagePath,input.tourId,["pdf"]);if(!uuid.safeParse(input.tourId).success||!valid||input.mimeType!=="application/pdf"||input.fileSize<=0||input.fileSize>MAX_PDF_SIZE||!await mediaExists(input.storagePath)){if(valid)await removeMedia(input.storagePath);return failure("PDF bilgileri geçersiz.");}const tour=await first<{pdf_path:string|null}>("SELECT pdf_path FROM tours WHERE id=?",[input.tourId]);if(!tour){await removeMedia(input.storagePath);return failure("Tur kaydı bulunamadı.");}try{await run("UPDATE tours SET pdf_path=?,updated_at=? WHERE id=?",[input.storagePath,new Date().toISOString(),input.tourId]);}catch{await removeMedia(input.storagePath);return failure();}if(tour.pdf_path&&tour.pdf_path!==input.storagePath){try{await removeMedia(tour.pdf_path);}catch{await run("UPDATE tours SET pdf_path=?,updated_at=? WHERE id=? AND pdf_path=?",[tour.pdf_path,new Date().toISOString(),input.tourId,input.storagePath]);await removeMedia(input.storagePath);return failure("Eski PDF silinemediği için değişiklik tamamlanamadı.");}}refresh(input.tourId);return success(tour.pdf_path?"PDF değiştirildi.":"PDF yüklendi.");}
export async function deleteTourPdfAction(tourId:string){await requireAdmin();if(!uuid.safeParse(tourId).success)return failure("Geçersiz tur kaydı.");const tour=await first<{pdf_path:string|null}>("SELECT pdf_path FROM tours WHERE id=?",[tourId]);if(!tour?.pdf_path||!isValidTourStoragePath(tour.pdf_path,tourId,["pdf"]))return failure("Bu tura ait PDF bulunamadı.");try{await removeMedia(tour.pdf_path);}catch{return failure("PDF dosyası silinemedi.");}await run("UPDATE tours SET pdf_path=NULL,updated_at=? WHERE id=?",[new Date().toISOString(),tourId]);refresh(tourId);return success("PDF silindi.");}
