"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createHotelAction, deleteHotelAction, moveHotelAction, updateHotelAction, type ContentActionResult } from "@/app/admin/(protected)/turlar/content-actions";
import { ActionMessage, inputClass, MoveButtons } from "@/components/admin/tours/content/content-controls";
import { ConfirmDeleteDialog } from "@/components/admin/tours/content/confirm-delete-dialog";
import type { HotelAdminRow as Row } from "@/types/admin-db";
type FormValue = { city: string; hotel_name: string; night_count: string; stars: string };
const empty = (): FormValue => ({ city: "", hotel_name: "", night_count: "1", stars: "" });

export function HotelsManager({ tourId, hotels }: { tourId: string; hotels: readonly Row[] }) {
  const router = useRouter(); const [editing, setEditing] = useState<string | "new" | null>(null); const [form, setForm] = useState(empty); const [result, setResult] = useState<ContentActionResult | null>(null); const [deleting, setDeleting] = useState<Row | null>(null); const [pending, startTransition] = useTransition();
  function run(action: () => Promise<ContentActionResult>, close = false) { startTransition(async () => { const next = await action(); setResult(next); if (next.success) { if (close) setEditing(null); router.refresh(); } }); }
  return <div className="space-y-4"><ActionMessage result={result} /><button type="button" disabled={pending || editing === "new"} onClick={() => { setEditing("new"); setForm(empty()); setResult(null); }} className="min-h-11 rounded-md bg-brand px-5 text-sm font-bold text-white disabled:opacity-50">Konaklama Ekle</button>{editing === "new" && <HotelForm value={form} setValue={setForm} errors={result?.success === false ? result.fieldErrors : {}} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => createHotelAction(tourId, form), true)} />}
  <div className="grid gap-3 md:grid-cols-2">{hotels.map((hotel, index) => editing === hotel.id ? <HotelForm key={hotel.id} value={form} setValue={setForm} errors={result?.success === false ? result.fieldErrors : {}} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => updateHotelAction(tourId, hotel.id, form), true)} /> : <article key={hotel.id} className="rounded-md border border-border bg-background p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold">{hotel.city}</h3><p className="mt-1 text-sm text-muted">{hotel.hotel_name}</p><p className="mt-2 text-sm font-semibold">{hotel.night_count} gece{hotel.stars ? ` · ${hotel.stars} yıldız` : ""}</p></div><MoveButtons first={index === 0} last={index === hotels.length - 1} busy={pending} onPrevious={() => run(() => moveHotelAction(tourId, hotel.id, "previous"))} onNext={() => run(() => moveHotelAction(tourId, hotel.id, "next"))} /></div><div className="mt-4 flex gap-2"><button type="button" disabled={pending} onClick={() => { setEditing(hotel.id); setForm({ city: hotel.city, hotel_name: hotel.hotel_name, night_count: String(hotel.night_count), stars: hotel.stars ? String(hotel.stars) : "" }); setResult(null); }} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">Düzenle</button><button type="button" disabled={pending} onClick={() => setDeleting(hotel)} className="px-3 text-sm font-bold text-brand">Sil</button></div></article>)}</div>{hotels.length === 0 && editing !== "new" && <p className="rounded-md bg-background p-5 text-center text-sm text-muted">Henüz konaklama eklenmedi.</p>}<ConfirmDeleteDialog open={Boolean(deleting)} title="Konaklama silinsin mi?" description={deleting ? `${deleting.city} — ${deleting.hotel_name}` : ""} busy={pending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && run(async () => { const next = await deleteHotelAction(tourId, deleting.id); if (next.success) setDeleting(null); return next; })} /></div>;
}

function HotelForm({ value, setValue, errors, busy, onCancel, onSubmit }: { value: FormValue; setValue: React.Dispatch<React.SetStateAction<FormValue>>; errors: Record<string, string>; busy: boolean; onCancel: () => void; onSubmit: () => void }) { return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="grid gap-3 rounded-md border border-brand/20 bg-brand/2 p-4 sm:grid-cols-2"><Field label="Şehir" error={errors.city}><input required maxLength={100} value={value.city} onChange={(event) => setValue((current) => ({ ...current, city: event.target.value }))} className={inputClass} /></Field><Field label="Otel" error={errors.hotel_name}><input required maxLength={180} value={value.hotel_name} onChange={(event) => setValue((current) => ({ ...current, hotel_name: event.target.value }))} className={inputClass} /></Field><Field label="Gece" error={errors.night_count}><input required type="number" min="1" max="60" value={value.night_count} onChange={(event) => setValue((current) => ({ ...current, night_count: event.target.value }))} className={inputClass} /></Field><Field label="Yıldız" error={errors.stars}><select value={value.stars} onChange={(event) => setValue((current) => ({ ...current, stars: event.target.value }))} className={inputClass}><option value="">Belirtilmedi</option>{[1,2,3,4,5].map((star) => <option key={star} value={star}>{star} yıldız</option>)}</select></Field><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={onCancel} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">Vazgeç</button><button disabled={busy} className="min-h-10 rounded-md bg-brand px-4 text-sm font-bold text-white">{busy ? "Kaydediliyor…" : "Kaydet"}</button></div></form>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="text-sm font-semibold">{label}<span className="mt-1.5 block">{children}</span>{error && <span className="mt-1 block text-xs text-brand">{error}</span>}</label>; }
