"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createImportantNoteAction, deleteImportantNoteAction, moveImportantNoteAction, updateImportantNoteAction, type ContentActionResult } from "@/app/admin/(protected)/turlar/content-actions";
import { ActionMessage, inputClass, MoveButtons, textareaClass } from "@/components/admin/tours/content/content-controls";
import { ConfirmDeleteDialog } from "@/components/admin/tours/content/confirm-delete-dialog";
import type { NoteAdminRow as Row } from "@/types/admin-db";
type Form = { title: string; content: string }; const empty = (): Form => ({ title: "", content: "" });

export function ImportantNotesManager({ tourId, notes }: { tourId: string; notes: readonly Row[] }) {
  const router = useRouter(); const [editing, setEditing] = useState<string | "new" | null>(null); const [form, setForm] = useState(empty); const [result, setResult] = useState<ContentActionResult | null>(null); const [deleting, setDeleting] = useState<Row | null>(null); const [pending, startTransition] = useTransition();
  function run(action: () => Promise<ContentActionResult>, close = false) { startTransition(async () => { const next = await action(); setResult(next); if (next.success) { if (close) setEditing(null); router.refresh(); } }); }
  return <div className="space-y-4"><ActionMessage result={result} /><button type="button" disabled={pending || editing === "new"} onClick={() => { setEditing("new"); setForm(empty()); setResult(null); }} className="min-h-11 rounded-md bg-brand px-5 text-sm font-bold text-white disabled:opacity-50">Önemli Bilgi Ekle</button>{editing === "new" && <NoteForm value={form} setValue={setForm} errors={result?.fieldErrors ?? {}} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => createImportantNoteAction(tourId, form), true)} />}<div className="space-y-3">{notes.map((note, index) => editing === note.id ? <NoteForm key={note.id} value={form} setValue={setForm} errors={result?.fieldErrors ?? {}} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => updateImportantNoteAction(tourId, note.id, form), true)} /> : <article key={note.id} className="rounded-md border border-border bg-background p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-extrabold">{note.title || "Önemli Bilgi"}</h3><p className="mt-2 line-clamp-3 whitespace-pre-line text-sm leading-6 text-muted">{note.content}</p></div><MoveButtons first={index === 0} last={index === notes.length - 1} busy={pending} onPrevious={() => run(() => moveImportantNoteAction(tourId, note.id, "previous"))} onNext={() => run(() => moveImportantNoteAction(tourId, note.id, "next"))} /></div><div className="mt-3 flex gap-2"><button type="button" onClick={() => { setEditing(note.id); setForm({ title: note.title ?? "", content: note.content }); setResult(null); }} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">Düzenle</button><button type="button" onClick={() => setDeleting(note)} className="px-3 text-sm font-bold text-brand">Sil</button></div></article>)}</div><ConfirmDeleteDialog open={Boolean(deleting)} title="Önemli bilgi silinsin mi?" description={deleting?.title || "Önemli Bilgi"} busy={pending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && run(async () => { const next = await deleteImportantNoteAction(tourId, deleting.id); if (next.success) setDeleting(null); return next; })} /></div>;
}
function NoteForm({ value, setValue, errors, busy, onCancel, onSubmit }: { value: Form; setValue: React.Dispatch<React.SetStateAction<Form>>; errors: Record<string, string>; busy: boolean; onCancel: () => void; onSubmit: () => void }) { return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="space-y-3 rounded-md border border-brand/20 bg-brand/2 p-4"><label className="block text-sm font-semibold">Başlık (opsiyonel)<input value={value.title} maxLength={160} onChange={(event) => setValue((current) => ({ ...current, title: event.target.value }))} className={`mt-1.5 ${inputClass}`} />{errors.title && <span className="mt-1 block text-xs text-brand">{errors.title}</span>}</label><label className="block text-sm font-semibold">Açıklama<textarea required value={value.content} maxLength={4000} rows={5} onChange={(event) => setValue((current) => ({ ...current, content: event.target.value }))} className={`mt-1.5 ${textareaClass}`} />{errors.content && <span className="mt-1 block text-xs text-brand">{errors.content}</span>}</label><div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">Vazgeç</button><button disabled={busy} className="min-h-10 rounded-md bg-brand px-4 text-sm font-bold text-white">{busy ? "Kaydediliyor…" : "Kaydet"}</button></div></form>; }
