"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createServiceAction, deleteServiceAction, moveServiceAction, updateServiceAction, type ContentActionResult } from "@/app/admin/(protected)/turlar/content-actions";
import { ActionMessage, MoveButtons, textareaClass } from "@/components/admin/tours/content/content-controls";
import { ConfirmDeleteDialog } from "@/components/admin/tours/content/confirm-delete-dialog";
import type { Database } from "@/types/database.types";

type Row = Database["public"]["Tables"]["tour_service_items"]["Row"];
type ServiceType = "included" | "excluded";

export function ServicesManager({ tourId, services }: { tourId: string; services: readonly Row[] }) {
  const router = useRouter(); const [editing, setEditing] = useState<{ type: ServiceType; id: string | "new" } | null>(null); const [content, setContent] = useState(""); const [result, setResult] = useState<ContentActionResult | null>(null); const [deleting, setDeleting] = useState<Row | null>(null); const [pending, startTransition] = useTransition();
  function run(action: () => Promise<ContentActionResult>, close = false) { startTransition(async () => { const next = await action(); setResult(next); if (next.success) { if (close) setEditing(null); router.refresh(); } }); }
  return <div className="space-y-4"><ActionMessage result={result} /><div className="grid min-w-0 gap-5 lg:grid-cols-2">{(["included", "excluded"] as const).map((type) => { const rows = services.filter((item) => item.type === type); return <section key={type} className="min-w-0 rounded-md border border-border bg-background p-4" aria-labelledby={`services-${type}`}><div className="flex items-center justify-between gap-3"><h3 id={`services-${type}`} className="font-extrabold">{type === "included" ? "Fiyata Dahil" : "Fiyata Dahil Değil"}</h3><span className="rounded-full bg-surface px-2.5 py-1 text-xs font-bold text-muted">{rows.length}</span></div><button type="button" disabled={pending || editing?.type === type} onClick={() => { setEditing({ type, id: "new" }); setContent(""); setResult(null); }} className="mt-3 min-h-10 rounded-md border border-brand/30 px-4 text-sm font-bold text-brand disabled:opacity-50">Madde Ekle</button>{editing?.type === type && editing.id === "new" && <ServiceForm content={content} setContent={setContent} error={result?.fieldErrors.content} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => createServiceAction(tourId, type, { content }), true)} />}<div className="mt-4 space-y-2">{rows.map((item, index) => editing?.id === item.id ? <ServiceForm key={item.id} content={content} setContent={setContent} error={result?.fieldErrors.content} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => updateServiceAction(tourId, item.id, type, { content }), true)} /> : <article key={item.id} className="rounded-md border border-border bg-surface p-3"><p className="text-sm leading-6">{item.content}</p><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><MoveButtons first={index === 0} last={index === rows.length - 1} busy={pending} onPrevious={() => run(() => moveServiceAction(tourId, item.id, type, "previous"))} onNext={() => run(() => moveServiceAction(tourId, item.id, type, "next"))} /><div><button type="button" disabled={pending} onClick={() => { setEditing({ type, id: item.id }); setContent(item.content); setResult(null); }} className="min-h-10 px-3 text-sm font-bold">Düzenle</button><button type="button" disabled={pending} onClick={() => setDeleting(item)} className="min-h-10 px-3 text-sm font-bold text-brand">Sil</button></div></div></article>)}</div></section>; })}</div><ConfirmDeleteDialog open={Boolean(deleting)} title="Hizmet maddesi silinsin mi?" description={deleting?.content ?? ""} busy={pending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && run(async () => { const type = deleting.type === "included" ? "included" : "excluded"; const next = await deleteServiceAction(tourId, deleting.id, type); if (next.success) setDeleting(null); return next; })} /></div>;
}

function ServiceForm({ content, setContent, error, busy, onCancel, onSubmit }: { content: string; setContent: (value: string) => void; error?: string; busy: boolean; onCancel: () => void; onSubmit: () => void }) { return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="mt-3 rounded-md border border-brand/20 bg-brand/2 p-3"><label className="text-sm font-semibold">Hizmet maddesi<textarea required maxLength={600} rows={3} value={content} onChange={(event) => setContent(event.target.value)} className={`mt-1.5 ${textareaClass}`} /></label>{error && <p className="mt-1 text-xs text-brand">{error}</p>}<div className="mt-3 flex justify-end gap-2"><button type="button" onClick={onCancel} className="min-h-10 rounded-md border border-border px-3 text-sm font-bold">Vazgeç</button><button disabled={busy} className="min-h-10 rounded-md bg-brand px-3 text-sm font-bold text-white">{busy ? "Kaydediliyor…" : "Kaydet"}</button></div></form>; }
