"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createFaqAction, deleteFaqAction, moveFaqAction, toggleFaqPublishedAction, updateFaqAction, type ContentActionResult } from "@/app/admin/(protected)/turlar/content-actions";
import { ActionMessage, inputClass, MoveButtons, textareaClass } from "@/components/admin/tours/content/content-controls";
import { ConfirmDeleteDialog } from "@/components/admin/tours/content/confirm-delete-dialog";
import type { Database } from "@/types/database.types";
type Row = Database["public"]["Tables"]["tour_faqs"]["Row"];
type Form = { question: string; answer: string; published: boolean }; const empty = (): Form => ({ question: "", answer: "", published: true });

export function TourFaqsManager({ tourId, faqs }: { tourId: string; faqs: readonly Row[] }) {
  const router = useRouter(); const [editing, setEditing] = useState<string | "new" | null>(null); const [form, setForm] = useState(empty); const [result, setResult] = useState<ContentActionResult | null>(null); const [deleting, setDeleting] = useState<Row | null>(null); const [pending, startTransition] = useTransition();
  function run(action: () => Promise<ContentActionResult>, close = false) { startTransition(async () => { const next = await action(); setResult(next); if (next.success) { if (close) setEditing(null); router.refresh(); } }); }
  return <div className="space-y-4"><ActionMessage result={result} /><button type="button" disabled={pending || editing === "new"} onClick={() => { setEditing("new"); setForm(empty()); setResult(null); }} className="min-h-11 rounded-md bg-brand px-5 text-sm font-bold text-white disabled:opacity-50">SSS Ekle</button>{editing === "new" && <FaqForm value={form} setValue={setForm} errors={result?.fieldErrors ?? {}} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => createFaqAction(tourId, form), true)} />}<div className="space-y-3">{faqs.map((faq, index) => editing === faq.id ? <FaqForm key={faq.id} value={form} setValue={setForm} errors={result?.fieldErrors ?? {}} busy={pending} onCancel={() => setEditing(null)} onSubmit={() => run(() => updateFaqAction(tourId, faq.id, form), true)} /> : <article key={faq.id} className="rounded-md border border-border bg-background p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{faq.question}</h3><span className={`rounded-full px-2 py-0.5 text-xs font-bold ${faq.published ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700"}`}>{faq.published ? "Yayında" : "Taslak"}</span></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted">{faq.answer}</p></div><MoveButtons first={index === 0} last={index === faqs.length - 1} busy={pending} onPrevious={() => run(() => moveFaqAction(tourId, faq.id, "previous"))} onNext={() => run(() => moveFaqAction(tourId, faq.id, "next"))} /></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => { setEditing(faq.id); setForm({ question: faq.question, answer: faq.answer, published: faq.published }); setResult(null); }} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">Düzenle</button><button type="button" disabled={pending} onClick={() => run(() => toggleFaqPublishedAction(tourId, faq.id, !faq.published))} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">{faq.published ? "Taslağa Al" : "Yayınla"}</button><button type="button" onClick={() => setDeleting(faq)} className="px-3 text-sm font-bold text-brand">Sil</button></div></article>)}</div><ConfirmDeleteDialog open={Boolean(deleting)} title="SSS silinsin mi?" description={deleting?.question ?? ""} busy={pending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && run(async () => { const next = await deleteFaqAction(tourId, deleting.id); if (next.success) setDeleting(null); return next; })} /></div>;
}
function FaqForm({ value, setValue, errors, busy, onCancel, onSubmit }: { value: Form; setValue: React.Dispatch<React.SetStateAction<Form>>; errors: Record<string, string>; busy: boolean; onCancel: () => void; onSubmit: () => void }) { return <form onSubmit={(event) => { event.preventDefault(); onSubmit(); }} className="space-y-3 rounded-md border border-brand/20 bg-brand/2 p-4"><label className="block text-sm font-semibold">Soru<input required value={value.question} maxLength={250} onChange={(event) => setValue((current) => ({ ...current, question: event.target.value }))} className={`mt-1.5 ${inputClass}`} />{errors.question && <span className="mt-1 block text-xs text-brand">{errors.question}</span>}</label><label className="block text-sm font-semibold">Cevap<textarea required value={value.answer} maxLength={5000} rows={5} onChange={(event) => setValue((current) => ({ ...current, answer: event.target.value }))} className={`mt-1.5 ${textareaClass}`} />{errors.answer && <span className="mt-1 block text-xs text-brand">{errors.answer}</span>}</label><label className="flex min-h-10 items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={value.published} onChange={(event) => setValue((current) => ({ ...current, published: event.target.checked }))} className="size-4 accent-brand" />Yayında</label><div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="min-h-10 rounded-md border border-border px-4 text-sm font-bold">Vazgeç</button><button disabled={busy} className="min-h-10 rounded-md bg-brand px-4 text-sm font-bold text-white">{busy ? "Kaydediliyor…" : "Kaydet"}</button></div></form>; }
